import { useCallback, useEffect, useState } from 'react'

import { Check, LoaderCircle } from '../../icons'
import { toUserMessage } from '../../shared/api/errors'
import { ErrorBanner } from '../../shared/ui/Feedback'
import { complianceApi } from '../compliance/api/complianceApi'
import { ConfirmationDialog } from '../organizations/components/ConfirmationDialog'
import { retentionApi } from './api/retentionApi'

const RESOURCES = ['prospect', 'contact', 'contact_channel', 'acquisition_record', 'provenance_record', 'import_declaration']
const FIELDS = [['business_name', 'Nom établissement'], ['business_address', 'Adresse'], ['contact_name', 'Nom contact'], ['email', 'Courriel'], ['phone', 'Téléphone'], ['linkedin_profile', 'LinkedIn']]
const CATEGORIES = [['business_identity', 'Identité établissement'], ['person_identity', 'Identité personne'], ['email', 'Courriel'], ['phone', 'Téléphone'], ['social_profile', 'Profil social']]

export function RetentionImportsPage({ session }) {
  const [tab, setTab] = useState('policies')
  const [data, setData] = useState({ policies: [], reviews: [], holds: [], imports: [], acquisitions: [] })
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [confirm, setConfirm] = useState(null)
  const canManage = session.capabilities.includes('retention:manage'); const canHold = session.capabilities.includes('retention:hold:create'); const canRelease = session.capabilities.includes('retention:hold:release'); const canDeclare = session.capabilities.includes('imports:declare'); const canArchive = session.capabilities.includes('imports:archive')
  const load = useCallback(async () => { setLoading(true); try { const [policies, reviews, holds, imports, acquisitions] = await Promise.all([retentionApi.listPolicies(), retentionApi.listReviews(), retentionApi.listHolds(), retentionApi.listImports(), complianceApi.listAcquisitions()]); setData({ policies: policies.items ?? [], reviews: reviews.items ?? [], holds: holds.items ?? [], imports: imports.items ?? [], acquisitions: acquisitions.items ?? [] }); setError('') } catch (cause) { setError(toUserMessage(cause, 'Impossible de charger les données de conservation.')) } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  async function policy(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await retentionApi.createPolicy({ resource_type: form.get('resource_type'), policy_code: String(form.get('code')).trim(), label: String(form.get('label')).trim(), review_after_days: Number(form.get('review')), archive_after_days: form.get('archive') ? Number(form.get('archive')) : undefined }); setSuccess('Politique créée en brouillon.'); await load() } catch (cause) { setError(toUserMessage(cause)) } }
  async function hold(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await retentionApi.createHold({ resource_type: form.get('resource_type'), resource_id: form.get('resource_id'), reason_code: form.get('reason'), note: String(form.get('note')).trim() || undefined }); setSuccess('Hold ajouté.'); await load() } catch (cause) { setError(toUserMessage(cause)) } }
  async function importDeclaration(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await retentionApi.createImport({ acquisition_record_id: form.get('acquisition'), declaration_label: String(form.get('label')).trim(), format_code: 'csv', schema_code: 'prospect_contacts_v1', declared_field_codes: form.getAll('field'), declared_data_categories: form.getAll('category'), estimated_row_count: form.get('rows') ? Number(form.get('rows')) : undefined }); setSuccess('Déclaration enregistrée : aucun fichier n’a été téléversé.'); await load() } catch (cause) { setError(toUserMessage(cause)) } }
  async function applyConfirmation() { if (!confirm) return; try { if (confirm.kind === 'activate') await retentionApi.activatePolicy(confirm.item.id, confirm.item.version); if (confirm.kind === 'release') await retentionApi.releaseHold(confirm.item.id, { version: confirm.item.version, release_reason_code: 'resolved' }); if (confirm.kind === 'cancel') await retentionApi.cancelImport(confirm.item.id, confirm.item.version); if (confirm.kind === 'archive') await retentionApi.archiveImport(confirm.item.id, { version: confirm.item.version, archive_reason_code: 'import_cancelled' }); setConfirm(null); setSuccess('Action enregistrée.'); await load() } catch (cause) { setConfirm(null); setError(toUserMessage(cause)) } }
  const list = (items, render) => <ul className="compliance-list">{items.map(render)}</ul>
  return <>
    <main className="administration-page retention-page" aria-labelledby="retention-title"><header className="administration-page-heading"><p className="eyebrow">Conservation et import</p><h1 id="retention-title">Conservation des données</h1><p>Les archivages sont logiques : aucune donnée n’est physiquement supprimée.</p></header>
      {error && <ErrorBanner><span>{error}</span></ErrorBanner>}{success && <div className="success-banner" role="status"><Check size={18}/><span>{success}</span></div>}
      <div className="administration-tabs" role="tablist"><button type="button" role="tab" aria-selected={tab === 'policies'} onClick={() => setTab('policies')}>Politiques</button><button type="button" role="tab" aria-selected={tab === 'holds'} onClick={() => setTab('holds')}>Holds et revues</button><button type="button" role="tab" aria-selected={tab === 'imports'} onClick={() => setTab('imports')}>Déclarations d’import</button></div>
      {loading ? <div className="administration-loading"><LoaderCircle className="spin" size={20}/> Chargement…</div> : <>
        {tab === 'policies' && <><section className="administration-card"><h2>Politiques</h2>{list(data.policies, (item) => <li key={item.id}><div><strong>{item.label}</strong><small>{item.resource_type} · revue après {item.review_after_days} jours</small><span className={`resource-status ${item.status}`}>{item.status}</span></div><div><small>Version {item.version}</small></div>{canManage && item.status === 'draft' && <button className="secondary-button" type="button" onClick={() => setConfirm({ kind: 'activate', item })}>Activer</button>}</li>)}</section>{canManage && <section className="administration-card compliance-form-card"><h2>Nouvelle politique</h2><form className="compliance-form compact-form" onSubmit={policy}><label>Ressource<select name="resource_type">{RESOURCES.map((x) => <option key={x}>{x}</option>)}</select></label><label>Code<input name="code" required/></label><label>Libellé<input name="label" required/></label><label>Revue (jours)<input name="review" type="number" min="1" required/></label><label>Archivage (jours)<input name="archive" type="number" min="1"/></label><button className="primary-button">Créer</button></form></section>}</>}
        {tab === 'holds' && <><section className="administration-card"><h2>Revue de conservation</h2>{list(data.reviews, (item, index) => <li key={`${item.resource_id}-${index}`}><div><strong>{item.resource_type}</strong><small>Échéance : {item.review_due_at?.slice(0, 10) ?? 'non définie'}</small></div><div><small>Holds actifs : {item.active_hold_count}</small><span className="resource-status">{item.review_state}</span></div></li>)}</section><section className="administration-card"><h2>Holds</h2>{list(data.holds, (item) => <li key={item.id}><div><strong>{item.resource_type}</strong><small>{item.reason_code}</small><span className={`resource-status ${item.released_at ? 'retired' : 'active'}`}>{item.released_at ? 'levé' : 'actif'}</span></div><div><small>{item.released_at ? `Levé le ${item.released_at.slice(0, 10)}` : 'Protection active'}</small></div>{canRelease && !item.released_at && <button className="secondary-button" type="button" onClick={() => setConfirm({ kind: 'release', item })}>Lever</button>}</li>)}</section>{canHold && <section className="administration-card compliance-form-card"><h2>Ajouter un hold</h2><form className="compliance-form" onSubmit={hold}><label>Ressource<select name="resource_type">{RESOURCES.map((x) => <option key={x}>{x}</option>)}</select></label><label>Identifiant<input name="resource_id" required/></label><label>Motif<select name="reason"><option value="legal_request">Demande légale</option><option value="quality_review">Revue qualité</option><option value="other">Autre</option></select></label><label>Note<input name="note" maxLength="500"/></label><button className="primary-button">Ajouter</button></form></section>}</>}
        {tab === 'imports' && <><section className="administration-card"><h2>Déclarations d’import</h2><p className="form-help">Le téléversement et le traitement du fichier seront disponibles dans un prochain incrément.</p>{list(data.imports, (item) => <li key={item.id}><div><strong>{item.declaration_label}</strong><small>{item.format_code} · {item.estimated_row_count ?? 'volume non précisé'} lignes</small><span className={`resource-status ${item.status}`}>{item.status}</span></div><div><small>{item.decision_reason_codes.join(', ')}</small></div>{item.status === 'declared' && <div className="resource-actions"><button className="secondary-button" type="button" onClick={() => setConfirm({ kind: 'cancel', item })}>Annuler</button>{canArchive && <button className="danger-link" type="button" onClick={() => setConfirm({ kind: 'archive', item })}>Archiver</button>}</div>}</li>)}</section>{canDeclare && <section className="administration-card compliance-form-card"><h2>Déclarer un import CSV</h2><form className="compliance-form" onSubmit={importDeclaration}><label>Acquisition<select name="acquisition" required>{data.acquisitions.filter((item) => item.status === 'approved').map((item) => <option key={item.id} value={item.id}>{item.source_label}</option>)}</select></label><label>Libellé<input name="label" required/></label><label>Volume estimé<input name="rows" type="number" min="1"/></label><fieldset className="full"><legend>Champs déclarés</legend>{FIELDS.map(([value, label], index) => <label key={value}><input type="checkbox" name="field" value={value} defaultChecked={index === 0}/> {label}</label>)}</fieldset><fieldset className="full"><legend>Catégories déclarées</legend>{CATEGORIES.map(([value, label], index) => <label key={value}><input type="checkbox" name="category" value={value} defaultChecked={index === 0}/> {label}</label>)}</fieldset><button className="primary-button">Déclarer sans téléverser</button></form></section>}</>}
      </>}
    </main>
    {confirm && <ConfirmationDialog title="Confirmer cette action ?" confirmLabel="Confirmer" onCancel={() => setConfirm(null)} onConfirm={applyConfirmation}><p>Cette action est journalisée. Elle ne supprime aucune donnée physique.</p></ConfirmationDialog>}
  </>
}
