from typing import Protocol


class PasswordHasher(Protocol):
    async def hash(self, password: str) -> str: ...

    async def verify(self, password: str, encoded_hash: str) -> bool: ...

    async def verify_dummy(self, password: str) -> None: ...

    async def needs_rehash(self, encoded_hash: str) -> bool: ...
